{{- if .Values.config.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librecov.fullname" . }}-oidc
  labels:
    {{- include "librecov.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.config.oidc.clientSecret | quote }}
{{- end }}
---
{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librecov.fullname" . }}-database
  labels:
    {{- include "librecov.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.externalDatabase.password | quote }}
{{- end }}
