apiVersion: v2
name: librecov-helm
description: A Helm chart for LibreCov - Open source code coverage history viewer
type: application
version: 0.0.14
appVersion: "0.0.14"
keywords:
  - coverage
  - testing
  - ci-cd
home: https://github.com/Frantche/Librecov
sources:
  - https://github.com/Frantche/Librecov
maintainers:
  - name: Frantche
    url: https://github.com/Frantche
